Enable dependabot to automatically get dependency updates
jenkinsci/gradle-plugin pull request #101
Opened 2020-10-08 11:57 UTC by MRamonLeon

It would be great to have **Dependabot** configured to get dependencies updates filed automatically. This will help avoiding bugs or security vulnerabilities from old dependencies.

Some helpful documentation about Dependabot to fine adjust it if needed:

* Keeping your dependencies updated automatically: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/keeping-your-dependencies-updated-automatically
* Avoiding security vulnerabilities: https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/configuring-github-dependabot-security-updates
* Fine adjusting the configuration: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates

2020-10-16 07:58 UTC, MRamonLeon commented
cc: @gboissinot @wolfs

2020-11-18 15:36 UTC, jglick requested changes

2020-11-18 15:36 UTC, jglick commented on .github/dependabot.yml
> +  - package-ecosystem: "maven"
Uh, not going to work when deps are in `build.gradle`.

AFAIK use of Dependabot on Gradle-based Jenkins plugins is untested and may or may not work sanely at all.

2020-11-18 20:59 UTC, wolfs requested changes
AFAIK dependabot does not work with Gradle.

2020-11-18 22:10 UTC, jglick commented
> dependabot does not work with Gradle

Acc. to https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates#package-ecosystem `gradle` is an option. Whether the updates it would offer would be at all useful is another question.

2020-11-18 22:24 UTC, wolfs approved these changes
If it works for Gradle, we can try it out. Is the dependabot configuration valid for a Gradle build, or is there something special which needs to be added? Can we test the integration on this PR already?

2020-11-18 22:29 UTC, jglick commented
> Is the dependabot configuration valid for a Gradle build

If you changed where it says `maven` to `gradle`. :grin: 

> Can we test the integration on this PR already?

I am not aware of a way to test the integration—you just turn it on, and if you get a half dozen worthless PRs that you have to close, you tune it or turn it off.

2020-11-24 16:51 UTC, merged

2020-11-24 17:13 UTC, wolfs commented
@MRamonLeon @jglick I merged the PR and am now getting PRs to update dependencies. I don't want to update the Spock dependency, since it requires a too high Groovy version: https://github.com/jenkinsci/gradle-plugin/pull/103
How can I disable dependabot updates for this dependency?

2020-11-24 17:47 UTC, jglick commented
> How can I disable dependabot updates for this dependency?

https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates#ignore