Add CI auto injection custom value to build scans
jenkinsci/gradle-plugin pull request #190
Opened 2022-10-14 09:30 UTC by sorin-florea

- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did

2022-10-14 10:01 UTC, welandaz approved these changes

2022-10-14 10:28 UTC, lemeurherve commented
I would remove the .DS_Store file of this PR before merging it, it has nothing to do in repo.

2022-10-16 09:10 UTC, sorin-florea commented
@lemeurherve Good catch, removed and updated `.gitignore`

2022-10-16 19:01 UTC, guylabs requested changes
Some renamings of the variables.

2022-10-16 19:01 UTC, guylabs commented on src/main/java/hudson/plugins/gradle/injection/MavenBuildScanInjection.java
> +    public static final String JENKINS = "Jenkins";
```suggestion
    private static final String GRADLE_ENTERPRISE_ALLOW_UNTRUSTED_SERVER_PROPERTY_KEY = "gradle.enterprise.allowUntrustedServer";
    private static final String BUILD_SCAN_UPLOAD_IN_BACKGROUND_PROPERTY_KEY = "gradle.scan.uploadInBackground";
    private static final String MAVEN_EXT_CLASS_PATH_PROPERTY_KEY = "maven.ext.class.path";
    private static final String BUILD_SCAN_CI_AUTO_INJECTION_CUSTOM_VALUE_NAME = "scan.value.CI-auto-injection";
    public static final String BUILD_SCAN_CI_AUTO_INJECTION_CUSTOM_VALUE_VALUE = "Jenkins";
```

2022-10-16 19:01 UTC, guylabs commented on src/main/resources/hudson/plugins/gradle/injection/init-script.gradle
> +def JENKINS = 'Jenkins'
```suggestion
def CI_AUTO_INJECTION_CUSTOM_VALUE_NAME = 'CI-auto-injection'
def CI_AUTO_INJECTION_CUSTOM_VALUE_VALUE = 'Jenkins'
```

2022-10-17 06:07 UTC, facewindu approved these changes

2022-10-17 07:18 UTC, c00ler approved these changes

2022-10-17 08:05 UTC, guylabs approved these changes

2022-10-17 08:07 UTC, merged